//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassificationScheme
    {
        public ClassificationScheme()
        {
            this.LstClassifications = new HashSet<Classification>();
        }
    
        public int ClassificationSchemeId { get; set; }
        public string ClassificationSchemeNM { get; set; }
        public string ClassificationSchemeDesc { get; set; }
        public Nullable<byte> IsSystem { get; set; }
        public Nullable<byte> IsHeirarchy { get; set; }
        public string SchemeCD { get; set; }
        public string ShortNM { get; set; }
        public Nullable<System.DateTime> CrtdDT { get; set; }
        public Nullable<long> CrtdUID { get; set; }
        public string CrtdUserName { get; set; }
        public Nullable<System.DateTime> LstModDT { get; set; }
        public Nullable<long> LstModUID { get; set; }
        public string LstModUserName { get; set; }
    
        public virtual ICollection<Classification> LstClassifications { get; set; }
        public virtual User ObjCrtdUser { get; set; }
    }
}
