//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classification
    {
        public Classification()
        {
            this.LstChild = new HashSet<Classification>();
            this.LstContentItems = new HashSet<ContentItem>();
            this.LstDisplayContents = new HashSet<DisplayContent>();
            this.LstMicrosites = new HashSet<Microsite>();
            this.Products = new HashSet<Product>();
        }
    
        public int ClassificationId { get; set; }
        public Nullable<int> ParentClassificationId { get; set; }
        public string ParentName { get; set; }
        public string ClassificationNM { get; set; }
        public string ClassificationDesc { get; set; }
        public string ClassificationMetakeyword { get; set; }
        public string ClassificationMetaDes { get; set; }
        public int ClassificationSchemeId { get; set; }
        public string ClassificationCD { get; set; }
        public string FriendlyURL { get; set; }
        public byte IsEnabled { get; set; }
        public Nullable<byte> IsSystem { get; set; }
        public Nullable<System.DateTime> CrtdDT { get; set; }
        public Nullable<long> CrtdUID { get; set; }
        public string CrtdUserName { get; set; }
        public Nullable<System.DateTime> LstModDT { get; set; }
        public Nullable<long> LstModUID { get; set; }
        public string LstModUserName { get; set; }
        public string ShortNM { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public string I18N { get; set; }
    
        public virtual ICollection<Classification> LstChild { get; set; }
        public virtual Classification ObjPrent { get; set; }
        public virtual ClassificationScheme ObjClassificationScheme { get; set; }
        public virtual User ObjCrtdUser { get; set; }
        public virtual ICollection<ContentItem> LstContentItems { get; set; }
        public virtual ICollection<DisplayContent> LstDisplayContents { get; set; }
        public virtual ICollection<Microsite> LstMicrosites { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}
