//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config
    {
        public long Id { get; set; }
        public string site_url { get; set; }
        public string site_name { get; set; }
        public string site_email { get; set; }
        public string site_facebook { get; set; }
        public string site_stwitter { get; set; }
        public string site_skype { get; set; }
        public string site_google { get; set; }
        public string site_youtube { get; set; }
        public string site_googleanalytics { get; set; }
        public string site_copyright { get; set; }
        public string site_phone { get; set; }
        public string site_homephone { get; set; }
        public string site_homephone2 { get; set; }
        public string site_description { get; set; }
        public string site_metadatakeyword { get; set; }
        public string site_metadadescription { get; set; }
        public string site_logo_url { get; set; }
        public string site_favico_url { get; set; }
        public string site_full_adress { get; set; }
        public string site_ward { get; set; }
        public string site_street { get; set; }
        public string site_district { get; set; }
        public string site_city { get; set; }
        public Nullable<int> site_width_thumb { get; set; }
        public Nullable<int> site_height_thumb { get; set; }
        public Nullable<int> site_page_size { get; set; }
    }
}
