//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentTag
    {
        public long ObjcontentId { get; set; }
        public long TagId { get; set; }
        public Nullable<System.DateTime> CrtdDT { get; set; }
        public long ObjTypeId { get; set; }
    
        public virtual Tag ObjTag { get; set; }
    }
}
