//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentComment
    {
        public long CommentId { get; set; }
        public Nullable<long> ParentCommentId { get; set; }
        public Nullable<long> ContentObjId { get; set; }
        public string ContentObjName { get; set; }
        public string Title { get; set; }
        public string CommentText { get; set; }
        public string FullName { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<System.DateTime> CrtdDT { get; set; }
        public Nullable<System.DateTime> AprvdDT { get; set; }
        public Nullable<long> AprvdUID { get; set; }
        public string AprvdUerName { get; set; }
        public Nullable<long> StateId { get; set; }
        public string StateName { get; set; }
        public Nullable<System.Guid> CrtdGuestUserId { get; set; }
        public Nullable<long> LikeCount { get; set; }
        public Nullable<System.DateTime> LastLikedDT { get; set; }
        public string IPAddress { get; set; }
        public Nullable<int> ObjTypeId { get; set; }
        public string ObjTypeName { get; set; }
    }
}
