//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentPackage
    {
        public long ContentId { get; set; }
        public long PackageId { get; set; }
        public long ContentType { get; set; }
        public Nullable<long> StateId { get; set; }
        public string ContentName { get; set; }
        public string PackageName { get; set; }
    }
}
