//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountLike
    {
        public long Id { get; set; }
        public Nullable<long> IdMicrosite { get; set; }
        public Nullable<long> IdProduct { get; set; }
        public Nullable<long> IdUser { get; set; }
        public Nullable<System.DateTime> DateLike { get; set; }
        public Nullable<int> TypeId { get; set; }
    }
}
