//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CyptoItemPrice
    {
        public long CyptoItemPriceId { get; set; }
        public System.DateTime CyptoItemPriceUpdate { get; set; }
        public long id { get; set; }
        public string name { get; set; }
        public string symbol { get; set; }
        public string slug { get; set; }
        public bool is_active { get; set; }
        public Nullable<System.DateTime> first_historical_data { get; set; }
        public Nullable<System.DateTime> last_historical_data { get; set; }
        public Nullable<int> cmc_rank { get; set; }
        public Nullable<int> num_market_pairs { get; set; }
        public Nullable<long> circulating_supply { get; set; }
        public Nullable<long> total_supply { get; set; }
        public Nullable<long> max_supply { get; set; }
        public System.DateTime last_updated { get; set; }
        public double USD_price { get; set; }
        public Nullable<double> USD_volume_24h { get; set; }
        public Nullable<double> USD_percent_change_1h { get; set; }
        public Nullable<double> USD_percent_change_7d { get; set; }
        public Nullable<double> USD_market_cap { get; set; }
        public Nullable<double> BTC_price { get; set; }
        public Nullable<double> BTC_volume_24h { get; set; }
        public Nullable<double> BTC_percent_change_1h { get; set; }
        public Nullable<double> BTC_percent_change_7d { get; set; }
        public Nullable<double> BTC_market_cap { get; set; }
    }
}
