//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisplayContent
    {
        public int Id { get; set; }
        public Nullable<long> ContentId { get; set; }
        public Nullable<int> DisplayType { get; set; }
        public Nullable<int> ObjType { get; set; }
        public Nullable<System.DateTime> CrtdDT { get; set; }
        public Nullable<long> CrtdUID { get; set; }
        public Nullable<System.DateTime> StartDT { get; set; }
        public Nullable<System.DateTime> EndDT { get; set; }
        public string ShortNM { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
    
        public virtual Classification ObjDisplayType { get; set; }
    }
}
