//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExceptionLog
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> CrtdDT { get; set; }
        public string ErrorMessage { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public Nullable<long> UserId { get; set; }
    }
}
