//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        public long HotelId { get; set; }
        public string FriendlyURL { get; set; }
        public Nullable<long> ViewCount { get; set; }
        public Nullable<long> LikeCount { get; set; }
        public Nullable<long> CommentCount { get; set; }
        public Nullable<byte> IsCommentEnabled { get; set; }
        public Nullable<int> HotelType { get; set; }
        public string HotelTypeName { get; set; }
        public string HotelDetail { get; set; }
        public string HotelName { get; set; }
        public string HotelDes { get; set; }
        public string MetadataDesc { get; set; }
        public string MetadataKeyword { get; set; }
        public string MediaUrl { get; set; }
        public string MediaThumb { get; set; }
        public string CrtdUserName { get; set; }
        public Nullable<long> CrtdUserId { get; set; }
        public Nullable<System.DateTime> CrtdDT { get; set; }
        public string AprvdUserName { get; set; }
        public Nullable<long> AprvdUID { get; set; }
        public Nullable<System.DateTime> AprvdDT { get; set; }
        public string StateName { get; set; }
        public Nullable<long> StateId { get; set; }
        public Nullable<double> OldPrice { get; set; }
        public Nullable<double> NewPrice { get; set; }
        public string FullAdress { get; set; }
        public Nullable<int> District { get; set; }
        public string DistrictName { get; set; }
        public Nullable<int> City { get; set; }
        public string CitytName { get; set; }
        public Nullable<int> Ward { get; set; }
        public string WardName { get; set; }
        public string LocationCode { get; set; }
        public string Note { get; set; }
        public string Hotline1 { get; set; }
        public string Hotline2 { get; set; }
        public string HomePhone { get; set; }
        public string lng { get; set; }
        public string lat { get; set; }
        public string CheckInTime { get; set; }
        public string CheckOutTime { get; set; }
        public string Include { get; set; }
    }
}
