//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Margin
    {
        public long MarginId { get; set; }
        public string MarginName { get; set; }
        public Nullable<double> Long { get; set; }
        public Nullable<double> LongStop { get; set; }
        public Nullable<double> LongRate { get; set; }
        public string LongNote { get; set; }
        public Nullable<double> Short { get; set; }
        public Nullable<double> ShortStop { get; set; }
        public Nullable<double> ShortRate { get; set; }
        public string ShortNote { get; set; }
        public string CrtdUserName { get; set; }
        public Nullable<long> CrtdUserId { get; set; }
        public Nullable<System.DateTime> CrtdDT { get; set; }
        public string StateName { get; set; }
        public Nullable<long> StateId { get; set; }
        public string PackageName { get; set; }
        public Nullable<long> PackageId { get; set; }
        public Nullable<int> Flag { get; set; }
        public string ExContent { get; set; }
    }
}
