//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MediaContent
    {
        public long MediaContentId { get; set; }
        public System.Guid MediaContentGuidId { get; set; }
        public string Filename { get; set; }
        public string FullURL { get; set; }
        public string ThumbURL { get; set; }
        public string MetadataDesc { get; set; }
        public string MetadataKeyword { get; set; }
        public Nullable<long> MediaContentSize { get; set; }
        public string EXIFInfo { get; set; }
        public Nullable<int> MediaTypeId { get; set; }
        public Nullable<int> ObjTypeId { get; set; }
        public Nullable<long> AprvdUID { get; set; }
        public Nullable<System.DateTime> AprvdDT { get; set; }
        public Nullable<long> CrtdUID { get; set; }
        public Nullable<System.DateTime> CrtdDT { get; set; }
        public long ViewCount { get; set; }
        public string Caption { get; set; }
        public string AlternativeText { get; set; }
        public string MediaDesc { get; set; }
        public Nullable<long> ContentObjId { get; set; }
        public string ContentObjName { get; set; }
        public string LinkHref { get; set; }
    }
}
