//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Microsite
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string CreatUserName { get; set; }
        public Nullable<long> CreatUserId { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public string ApprUserName { get; set; }
        public Nullable<long> ApprUserId { get; set; }
        public string FullAdress { get; set; }
        public string HomePhone { get; set; }
        public string MobilePhone { get; set; }
        public string Fax { get; set; }
        public string Facebook { get; set; }
        public string Google { get; set; }
        public string MapCode { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string LicensePP { get; set; }
        public string LicenseNbr { get; set; }
        public Nullable<System.DateTime> LicenseDate { get; set; }
        public string LicenseLocation { get; set; }
        public string CMDDNbr { get; set; }
        public Nullable<System.DateTime> CMDDDate { get; set; }
        public string CMDDLocation { get; set; }
        public Nullable<int> Type { get; set; }
        public string TypeName { get; set; }
        public Nullable<int> CataType { get; set; }
        public string CataTypeName { get; set; }
        public Nullable<int> NbrOfProduct { get; set; }
        public Nullable<int> NbrOfSussDeal { get; set; }
        public string ImgLogo { get; set; }
        public string ImgLogoThumb { get; set; }
        public string Description { get; set; }
        public string Metakeyword { get; set; }
        public string MetaDescription { get; set; }
        public string FriendlyUrl { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string StatusName { get; set; }
        public string ColorTop { get; set; }
        public string ColorBottom { get; set; }
        public Nullable<long> OwnerId { get; set; }
        public string OwnerName { get; set; }
        public string ColorTextTop { get; set; }
        public string ColorTextBottom { get; set; }
    
        public virtual Classification ObjClassificationType { get; set; }
    }
}
