//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjectRelate
    {
        public long id { get; set; }
        public Nullable<long> ObjContentId { get; set; }
        public string ObjContentName { get; set; }
        public Nullable<int> ClassType { get; set; }
        public string ClassTypeName { get; set; }
        public Nullable<int> ObjType { get; set; }
        public string ObjTypeName { get; set; }
    }
}
