//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductInforExt
    {
        public long id { get; set; }
        public Nullable<long> ProductId { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> Size { get; set; }
        public Nullable<int> Color { get; set; }
        public string SKU { get; set; }
        public string ColorName { get; set; }
        public string SizeName { get; set; }
    }
}
