//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelatedContentItem
    {
        public long SubjectContentItemId { get; set; }
        public long ObjContentItemId { get; set; }
        public Nullable<System.DateTime> CrtdDT { get; set; }
        public Nullable<byte> IsDisabled { get; set; }
        public int ContentRelatedTypeId { get; set; }
    }
}
