//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.Users = new HashSet<User>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string RoleDes { get; set; }
        public Nullable<int> isPermission { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
