//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingAddress
    {
        public long LocationId { get; set; }
        public string LocationName { get; set; }
        public string Address { get; set; }
        public Nullable<int> CityId { get; set; }
        public int StatusId { get; set; }
        public string StatusName { get; set; }
        public string Zipcode { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> WardId { get; set; }
        public Nullable<int> StreetId { get; set; }
        public string Phone { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public string MapCode { get; set; }
    }
}
