//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public Tag()
        {
            this.LstContentTags = new HashSet<ContentTag>();
        }
    
        public long TagId { get; set; }
        public string TagNM { get; set; }
    
        public virtual ICollection<ContentTag> LstContentTags { get; set; }
    }
}
