//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        public long TourId { get; set; }
        public string FriendlyURL { get; set; }
        public string TourCD { get; set; }
        public Nullable<long> ViewCount { get; set; }
        public Nullable<long> LikeCount { get; set; }
        public Nullable<long> CommentCount { get; set; }
        public Nullable<byte> IsCommentEnabled { get; set; }
        public Nullable<int> TourType { get; set; }
        public string TourTypeName { get; set; }
        public string TourDetail { get; set; }
        public string TourName { get; set; }
        public string TourDes { get; set; }
        public string MetadataDesc { get; set; }
        public string MetadataKeyword { get; set; }
        public string MediaUrl { get; set; }
        public string MediaThumb { get; set; }
        public string CrtdUserName { get; set; }
        public Nullable<long> CrtdUserId { get; set; }
        public Nullable<System.DateTime> CrtdDT { get; set; }
        public string AprvdUserName { get; set; }
        public Nullable<long> AprvdUID { get; set; }
        public Nullable<System.DateTime> AprvdDT { get; set; }
        public string StateName { get; set; }
        public Nullable<long> StateId { get; set; }
        public Nullable<double> OldPrice { get; set; }
        public Nullable<double> NewPrice { get; set; }
        public string StartName { get; set; }
        public Nullable<int> StartId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string EndName { get; set; }
        public Nullable<int> EndId { get; set; }
        public Nullable<int> NumPeople { get; set; }
        public string GuideName { get; set; }
        public Nullable<long> GuideId { get; set; }
        public string Contact { get; set; }
        public string Including { get; set; }
        public string NotIncluding { get; set; }
        public string PartnerName { get; set; }
        public string PartnerAdress { get; set; }
        public string CancelTour { get; set; }
        public string ChangeTour { get; set; }
        public string Note { get; set; }
        public Nullable<int> TourClassId { get; set; }
        public string TourClassName { get; set; }
    }
}
