//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Userhist
    {
        public long Id { get; set; }
        public Nullable<long> CrtdUID { get; set; }
        public Nullable<System.DateTime> CrtdDT { get; set; }
        public string IPadress { get; set; }
        public Nullable<long> ActionObjId { get; set; }
        public Nullable<int> ActionTypeId { get; set; }
        public string Tablename { get; set; }
        public string FldName { get; set; }
        public string Oldvalue { get; set; }
        public string Newvalue { get; set; }
        public string ActionObjName { get; set; }
        public string ActionTypeName { get; set; }
        public Nullable<int> ObjTypeId { get; set; }
    
        public virtual User ObjCrtdUser { get; set; }
    }
}
