//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPackage
    {
        public long Id { get; set; }
        public string UpgradeUserName { get; set; }
        public Nullable<long> UpgradeUID { get; set; }
        public string AprvdUserName { get; set; }
        public Nullable<long> AprvdUID { get; set; }
        public Nullable<System.DateTime> AprvdDT { get; set; }
        public string StateName { get; set; }
        public Nullable<long> StateId { get; set; }
        public Nullable<long> PackageId { get; set; }
        public string PackageName { get; set; }
        public string UpgradeToken { get; set; }
        public Nullable<System.DateTime> CrtdDT { get; set; }
    }
}
