//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.LstClassifications = new HashSet<Classification>();
            this.LstClassificationSchemes = new HashSet<ClassificationScheme>();
            this.LstUserClaims = new HashSet<UserClaim>();
            this.LstUserhists = new HashSet<Userhist>();
            this.UserLogins = new HashSet<UserLogin>();
            this.LstRole = new HashSet<Role>();
            this.LstTransactionHis = new HashSet<TransactionHi>();
        }
    
        public long Id { get; set; }
        public string Login { get; set; }
        public string EMail { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public bool IsLocked { get; set; }
        public string PasswordQuestion { get; set; }
        public string PasswordAnswer { get; set; }
        public string ActivationToken { get; set; }
        public bool EmailConfirmed { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string FullName { get; set; }
        public Nullable<long> CMND { get; set; }
        public string FolerName { get; set; }
        public Nullable<int> GenderId { get; set; }
        public string GenderName { get; set; }
        public string OldPassword { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public string ActiveCode { get; set; }
        public Nullable<long> ParentID { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public string BankName { get; set; }
        public string BankAdress { get; set; }
        public string BankAccountHolder { get; set; }
        public string BankAccountNbr { get; set; }
        public Nullable<double> Money { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> CrtdDTCode { get; set; }
        public string Avatar { get; set; }
        public string UserAdress { get; set; }
        public string AccountName { get; set; }
    
        public virtual ICollection<Classification> LstClassifications { get; set; }
        public virtual ICollection<ClassificationScheme> LstClassificationSchemes { get; set; }
        public virtual ICollection<UserClaim> LstUserClaims { get; set; }
        public virtual ICollection<Userhist> LstUserhists { get; set; }
        public virtual ICollection<UserLogin> UserLogins { get; set; }
        public virtual ICollection<Role> LstRole { get; set; }
        public virtual ICollection<TransactionHi> LstTransactionHis { get; set; }
    }
}
